/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 28/07/2022 08:54:23          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'E:\cleite.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_COLETA_ID;
SET GENERATOR GEN_COLETA_ID TO 0;

CREATE GENERATOR GEN_PRODUTOR;
SET GENERATOR GEN_PRODUTOR TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE COLETA (
    ID           INTEGER NOT NULL,
    PRODCOD      INTEGER NOT NULL,
    QUANTIDADE   NUMERIC(15,3) NOT NULL,
    DATA_COLETA  DATE,
    DATA_PGT     DATE
);


CREATE TABLE CONFIG (
    ID          INTEGER NOT NULL,
    MODO        INTEGER,
    SPOOL       VARCHAR(30),
    PORTA       CHAR(5),
    VELOCIDADE  INTEGER,
    PARADA      INTEGER,
    BITS        INTEGER
);


CREATE TABLE PRODUTOR (
    ID             INTEGER NOT NULL,
    NOME           INTEGER,
    ULTIMA_COLETA  TIMESTAMP,
    ATIVO          SMALLINT
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE COLETA ADD CONSTRAINT PK_COLETA PRIMARY KEY (ID);
ALTER TABLE CONFIG ADD CONSTRAINT PK_CONFIG PRIMARY KEY (ID);
ALTER TABLE PRODUTOR ADD CONSTRAINT PK_PRODUTOR PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE COLETA ADD CONSTRAINT FK_COLETA_PRODUTOR FOREIGN KEY (PRODCOD) REFERENCES PRODUTOR (ID) ON UPDATE CASCADE;


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: COLETA_BI */
CREATE TRIGGER COLETA_BI FOR COLETA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_coleta_id,1);
end
^


/* Trigger: PRODUTOR_BI */
CREATE TRIGGER PRODUTOR_BI FOR PRODUTOR
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_produtor,1);
end
^


SET TERM ; ^
